[package]
name = "architecs"
version = "0.1.0"
edition = "2024"

[features]
default = ["winit"]
winit = ["dep:winit"]

[dependencies]
nalgebra = "0.34.1"
raw-window-handle = "0.6.2"
winit = { version = "0.30.12", optional = true }
